#!/usr/bin/env ruby

require "bundler/setup"
require_relative "../lib/data_files/repl.rb"

unless Dir.exist?(File.join(Dir.pwd, 'data'))
  puts 'Could not find data directory in working directory.'
  exit
end

data_files = DataFiles::REPL.new(Dir.pwd)
data_files.prompt
